#!/bin/bash
# Swarm Pulse - One-Click Setup for RL-Swarm
# Tek komutla her şeyi halleder!

set -e  # Hata olursa dur

echo "🌊 Swarm Pulse - Otomatik Kurulum Başlıyor..."
echo ""

# 1. rl-swarm container'ını bul
echo "🔍 RL-Swarm container aranıyor..."
CONTAINER=$(docker ps --filter "name=rl-swarm" --format "{{.Names}}" | head -n1)

if [ -z "$CONTAINER" ]; then
    echo "❌ RL-Swarm container bulunamadı!"
    echo "   Önce rl-swarm'ı başlatın:"
    echo "   cd ~/rl-swarm && docker-compose run --rm --build -Pit swarm-cpu"
    exit 1
fi

echo "✅ Container bulundu: $CONTAINER"
echo ""

# 2. Log dosyasını oluştur
LOG_FILE="$HOME/rl-swarm-logs.txt"
echo "📝 Log dosyası oluşturuluyor: $LOG_FILE"

# Eski log process'ini durdur
pkill -f "docker logs -f $CONTAINER" 2>/dev/null || true

# Yeni log stream başlat
nohup docker logs -f "$CONTAINER" > "$LOG_FILE" 2>&1 &
echo "✅ Docker logları dosyaya yönlendirildi"
echo ""

# 3. Config dosyasını otomatik oluştur
CONFIG_FILE="config.ini"
echo "⚙️  Config dosyası oluşturuluyor..."

cat > "$CONFIG_FILE" << EOF
[DEFAULT]
# Auto-generated by setup script
log_file_path = $LOG_FILE
auto_start = true
refresh_interval = 2
EOF

echo "✅ Config oluşturuldu: $CONFIG_FILE"
echo ""

# 4. Dependencies kontrol et
if ! command -v streamlit &> /dev/null; then
    echo "📦 Streamlit kuruluyor..."
    pip install -q -r requirements.txt
    echo "✅ Dependencies kuruldu"
else
    echo "✅ Dependencies zaten kurulu"
fi
echo ""

# 5. Streamlit'i başlat
echo "🚀 Swarm Pulse başlatılıyor..."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ KURULUM TAMAMLANDI!"
echo ""
echo "📊 Dashboard: http://localhost:8501"
echo "📁 Log dosyası: $LOG_FILE"
echo ""
echo "🔗 SSH Tunnel (local bilgisayardan):"
echo "   ssh -L 8501:localhost:8501 $(whoami)@$(hostname -I | awk '{print $1}')"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Streamlit'i başlat
streamlit run app.py --server.address=0.0.0.0 --server.port=8501
